sudo: required
dist: trusty
addons:
  chrome: stable
language: node_js
node_js:
  - 8
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_install:
  - cd gov-poc-ng
install:
  - npm install -g codecov
  - npm install coveralls
  - npm install
script:
  - npm run ci
after_script:
  - codecov
  - cat ./gov-poc-ng/node_modules/coveralls/bin/coveralls.js
